# config
model: cifar_resnet18
pretrained: false
num_classes: 10
opt: lion
lr: 1e-5
sched: cosine
epochs: 300
lr_min: 1e-5
warmup_lr: 1e-5
warmup_epochs: 30
t_in_epochs: true
batch_size: 100
data_path: './data'
seed: 42
output: './output'
